version: '2'

services:

  robopatrol:
    labels:
      ch.zhaw.description: "Launch robopatrol on a Turtlebot."
    image: robopatrol/webapp
    depends_on:
      - ros-turtlebot
      - server
    ports:
      - "9000:9000"

  robopatrol-simulation:
    labels:
      ch.zhaw.description: "Run robopatrol on a simulated Turtlebot."
    image: robopatrol/webapp
    depends_on:
      - ros-simulation
      - server
    ports:
      - "9000:9000"

# robopatrol-server (REST)
  server:
    image: robopatrol/server
    ports:
      - "9998:9998"

# robopatrol (ROS Bridge)
  ros-turtlebot:
    image: robopatrol/robopatrol
    command: "/bin/bash -c 'source ./devel/setup.bash && roslaunch robopatrol turtlebot.launch'"
    ports:
      - "9090:9090"
      - "11345:11345"
    depends_on:
      - server

# robopatrol (ROS Bridge, Gazebo)
  ros-simulation:
    image: robopatrol/robopatrol
    ports:
      - "9090:9090"
      - "11311:11311"
      - "11345:11345"
    depends_on:
      - server

